### ISSUE TITLE
A bug in FusorSV.py

### ISSUE THREAD

**Issue by hjzhou988** [timothyjamesbecker/FusorSV#1]
Hi,
Just report a bug in FusorSV.py line 114:
chroms = args.chrom.split(',')

I think it should be:
chroms = args.chroms.split(',')

**Comment by MaestSi** [comment]
Thanks for the information, I fixed it in my FusorSV.py script. However I think there are some other issues for running FusorSV on hg38 reference. Waiting for the compatibility issues to be fixed by developers. By the way, I think issues should be opened on SVE Github page, as this one is not mantained by them anymore.

**Comment by timothyjamesbecker** [comment]
This issue has been address in version 0.1.1.
