### ISSUE TITLE
FusorSV for Build38 data

### ISSUE THREAD

**Issue by lauracottino** [timothyjamesbecker/FusorSV#22]
Hi, apologies for previously posting this issue in the wrong repo.

We are having trouble getting FusorSV to run on Build38 data - SVE ran successfully but when we run FusorSV the resulting VCF file is empty. Is it possible to run it on Build38 data?

Thank you in advance.

**Comment by timothyjamesbecker** [comment]
Hello, the publication model was designed around the 1000 Genomes Phase 3 High Coverage dataset (27 samples from 26 human populations).  All callers in the publication will work with the reference fasta file they used in that paper, which was hg19 based.  The strategy we use is to then apply liftover to eliminate some of the SV calls that have been absorbed by the new reference (for example some DELs in hg19 are now part of Hg38).  You may have trouble using those callers on Hg38 or Grch38 variants (especially the alts).  For example, I am not aware of a Hg38 based BreakSeq2 junction library.  

That being said, the FusorSV hg19 based models will work well on Hg38 BAM data as long as the callers are properly making calls in the VCF format.  Delly, Lumpy, BreakDancer, CNVnator, and Hydra should all work fine on Hg38 and then you will be able to use FusorSV.  To do that you will need to prepare your reference files accordingly (since FusorSV relies on coordinate based data fusion).  If you are getting empty outputs the usual reason is that there is a reference to BAM file mismatch.  The same reference that was used in the SVE step must be also passed to FusorSV.  You will want to also craft or eliminate the svmask file which can also cause issues.

In particular you want to pay very close attention to the following arguments when using HG38 based seqs and coordinates:

FusorSV.py\
--in_dir /vcf_input_dir/ #must have all VCF in the correct reference coordinate system
--chroms chr1,chr2,   #not the default 1,2,3 from hg19!!!
--sv_mask svmask.bed #make or put together a sv_mask in the reference coordinate systems since the default is hg19!!!

For further help you can reply back to this same ISSUE with some of your command lines (remove the personal identifying or sample names in the command and replace with something generic like in my example above) so that I help trouble shoot.
