### ISSUE TITLE
numpy incompatibility with new model

### ISSUE THREAD

**Issue by arumds** [timothyjamesbecker/FusorSV#23]
Hi,

I have been using the fusorSVv0.1.4 built from the docker image and with the model `human_g1k_v37_decoy.S4_S10_S11_S17_S18_S48.pickle.gz` and having the below error:

```
Traceback (most recent call last):
  File "/usr/local/bin/FusorSV.py", line 488, in <module>
    B,J,D,E,alpha,n,K = fusor.import_fusion_model(apply_fusion_model_path)
  File "/usr/local/lib/python2.7/dist-packages/fusorsv/fusor_utils.py", line 229, in import_fusion_model
    P = pickle.load(f)
ImportError: No module named _multiarray_umath
```
Could you provide a solution to this issue?

**Comment by timothyjamesbecker** [comment]
I think this issue is backwards compatibility from the newer numpy library that has new unsigned math libraries for the array types used in the FusorSV framework.  The older numpy in the docker image does not have the new unsigned math libraries and causes Import Error.  I also noticed that FusorSV models built with newer numpy libraries are twice as large in size.  The older models work on the newer numpy but not the other way around.  I think newer numpy should not be used to build models and I can add a software check to provide the user more meaningful output than the import error.

**Comment by timothyjamesbecker** [comment]
Closing this issue as models trained with newer numpy will be compatible, while older models will need the older numpy version.
