### ISSUE TITLE
Training a model with an hg38 reference

### ISSUE THREAD

**Issue by lslochov** [timothyjamesbecker/FusorSV#3]
Hi, I've noticed in the main FusorSV code that the program imports hardcoded hg19 reference metadata. I am interested in training a FusorSV model with an hg38 reference. Can you please provide hg38 FusorSV-ready files?

**Comment by timothyjamesbecker** [comment]
As long as a model was trained using a similar reference you can reuse a model.  This is mainly because the FusorSV models do not include explicit reference information but if you are looking for the highest accuracy you would in fact want to train the model using the correct reference that you wish to apply.  The functionality to use arbitrary references is already in main libraries in the fusorsv folder.  Currently you would have to make the files and then change the main FusorSV.py script to point to them.  It sounds like you wish the main FusorSV.py script to build the reference coordinate metadata files for you so they could be passed as a command line argument.  I can add this in a future update to the main FusorSV.py script which will then make it easier to use any reference fasta file.

**Comment by timothyjamesbecker** [comment]
There is now user supplied coordinate maps in the main FusorSV.py script as of version 0.1.1.  This is not well tested as a system other than the human_g1k_v37_decoy reference set, but the script now will build coordinate maps for any fast file and now requires the user supply the svmask BED3 via the -m flag as a result.
