### ISSUE TITLE
Generation of SV mask files

### ISSUE THREAD

**Issue by lslochov** [timothyjamesbecker/FusorSV#9]
Hi, can you explain how the SV mask files that are available in `fusorsv/data` were generated?

**Comment by timothyjamesbecker** [comment]
The one that says lumpy was taken from the LUMPY paper, the ones that say
ucsc are taken from UCSC, the one that says human_g1k_v37_decoy_svmask.json
was taken from a genomestrip 2 analysis run which produces a fasta svmask.
The FusorSV framework has some utilities that convert fasta mask files
produced from genomestrip 2 analysis into coordinate ranges that can be
used in FusorSV.  Any svmask can be used with the current build 0.1.2 and
using information with regard to problematic areas of a genome build as a
mask will improve the training and in turn get better results from the
model.  These utilities can also be complemented meaning that if you define
areas that are part of lets say gene regions, you can do an analysis with
the parts of the genome that are not intersecting that mask.

**Comment by fpbarthel** [comment]
Hi! Thanks for your response. I have a similar question and am using the `human_g1k_v37_decoy_svmask.json` file (modified to fully exclude all extra contigs and the decoy contig) for LUMPY (converted to bed format), DELLY (converted to bed format, removing start/stop coordinates for fully excluded contigs) and Manta (converted to "include" file by taken the inverse). I am manually calling these tools with the intention to use FusorSV for integration. Are these files appropriate for this?

**Comment by timothyjamesbecker** [comment]
The model that is included was built from analysis on human_g1k_v37_decoy.fa and as such is designed to give a good result on that space.  If you deviate from the regions too much your result may not be the same in which case you would have to retrain a new model based on the new sv calls. Since the training mode is available to users, you could download the training data set in the releases section and build a new model using your custom mask.  Additionally if a new reference was desired you could also make use of coordinate liftover tools like crossmap to assit with this process. Yes you can just use the tools without the SVE and then FusorSV can put them together for you once you follow the folder and naming conventions.
